language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

before_script:
  - php -v
  - composer update $COMPOSER_PREFER

script:
  - vendor/bin/atoum --test-ext -p 'php -n -ddate.timezone=UTC'
